<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('airpapr-zend');

echo $this->doctype();
?>
<html>
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css'); ?>
</head>

<body>
<?php echo $this->partial('header.phtml'); ?>
<?php echo $this->placeholder('menu') ?>
<?php echo $this->layout()->content; ?>
<?php echo $this->partial('footer.phtml'); ?>
</body>

</html>